# Generated by Django 3.0.8 on 2020-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='friends',
            field=models.ManyToManyField(to='Auth.user_profile'),
        ),
    ]
