# Generated by Django 3.0.8 on 2020-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20201020_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Auth.user_profile'),
        ),
    ]
