# Generated by Django 3.0.8 on 2020-10-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20201020_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='friends',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='Auth.user_profile')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='Auth.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='Auth.Relationship', to='Auth.user_profile'),
        ),
    ]
