# Generated by Django 3.0.8 on 2020-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20201020_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='Auth.Relationship', to='Auth.user_profile'),
        ),
    ]
