# Generated by Django 3.0.8 on 2020-10-13 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 16, 58, 57, 808242)),
        ),
    ]
