# Generated by Django 3.1.1 on 2020-10-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201013_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
