# Generated by Django 3.1.1 on 2020-09-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(blank=True, upload_to='thumbpath')),
                ('caption', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
