# Generated by Django 3.1.1 on 2020-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='caption',
            field=models.CharField(max_length=20000),
        ),
    ]
